### ISSUE TITLE
Add ability to return Promises from controllers

### ISSUE THREAD

**Issue by alexmorbo** [CommandString/Router#2]
Hi!

For now I cant find a way to return promises from controllers to HttpServer.
Is there a plans for that?

I make some changes in my fork and in works for me.
You can look

**Comment by CommandString** [comment]
Not sure why you would want to return a promise? Could you further explain why?

Oh I see, I overlooked the fact you can return an PromiseInterface in the HTTP docs. Could you open a PR? I'd be happy to merge your changes.

**Comment by alexmorbo** [comment]
Yes, I will make a PR, but I think it better to make more tests with my changes, because I make it fast for my app :)

**Comment by CommandString** [comment]
If you wanna make tests for this then be my guest. I'm not too familiar with PHPUnit.
